# Generated by Django 4.2.2 on 2023-08-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_table_user_delete_table_cake'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_user',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
